export {
  AGGREGATION_PRIORITY_FIELDS,
  type AggregationPriorityFieldDefinition,
  FIELD_KEYS,
  FIELD_REGISTRY,
  FIELD_REGISTRY_BY_KEY,
  type FieldAnchor,
  type FieldEntry,
  type FieldSurface,
  type FieldVisibility,
  flattenConfig,
  getNestedValue,
  isFieldManagedBySettingsSearch,
  isRecord,
  SECTION_FILTER_ALIASES,
  SECTION_LABELS,
  SECTION_ORDER,
  SETTINGS_FIELD_REGISTRY,
  setNestedValue,
  unflattenConfig,
} from "@mdcz/shared/settingsRegistry";
